// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DataAccessContext))]
    partial class DataAccessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Infrastructure.Models.ArtikliModel", b =>
                {
                    b.Property<long>("PkArtikliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("FkJedinicaMjereId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkArtikliId");

                    b.HasIndex("FkJedinicaMjereId");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.Atributi", b =>
                {
                    b.Property<long>("PkAtributId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FkJedinicaMjereId")
                        .HasColumnType("bigint");

                    b.Property<string>("JedinicaMjere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkAtributId");

                    b.ToTable("Atributi");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.AtributiArtikla", b =>
                {
                    b.Property<long>("PkFkArtikalId")
                        .HasColumnType("bigint");

                    b.Property<long>("PkFkAtributId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkFkArtikalId", "PkFkAtributId");

                    b.HasIndex("PkFkAtributId");

                    b.ToTable("AtributiArtikla");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.JediniceMjere", b =>
                {
                    b.Property<long>("PkJedinicaMjereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkJedinicaMjereId");

                    b.ToTable("JediniceMjere");
                });

            modelBuilder.Entity("DataAccess.UserManagement.Models.ApplicationUser", b =>
                {
                    b.Property<int>("PkUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.ArtikliModel", b =>
                {
                    b.HasOne("DataAccess.Infrastructure.Models.JediniceMjere", "JedinicaMjere")
                        .WithMany()
                        .HasForeignKey("FkJedinicaMjereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JedinicaMjere");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.AtributiArtikla", b =>
                {
                    b.HasOne("DataAccess.Infrastructure.Models.ArtikliModel", "Artikal")
                        .WithMany("AtributiArtikla")
                        .HasForeignKey("PkFkArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Infrastructure.Models.Atributi", "Atribut")
                        .WithMany("ArtikliAtributa")
                        .HasForeignKey("PkFkAtributId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Atribut");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.ArtikliModel", b =>
                {
                    b.Navigation("AtributiArtikla");
                });

            modelBuilder.Entity("DataAccess.Infrastructure.Models.Atributi", b =>
                {
                    b.Navigation("ArtikliAtributa");
                });
#pragma warning restore 612, 618
        }
    }
}
